---
abstract: 'Create a pan genome'
author:
  - Me
build_requires:
  Data::Dumper: '0'
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bio-Test
requires:
  Acme::ProgressBar: '1.002'
  File::Slurp: '0'
  Moose: '0'
  Sub::Exporter: '0.979'
  YAML::XS: '0'
  strict: '0'
  warnings: '0'
version: '0.001'
